[build]
# Force using custom Dockerfile - disable auto-detection completely
dockerfile = "Dockerfile"
buildCommand = "docker build -f Dockerfile -t app ."

[variables]
# Disable all browser installations and auto-detection
NIXPACKS_NO_BROWSER_INSTALL = "1"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "1"
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"

# Disable provider auto-detection to force using Dockerfile
[providers]
node = false
npm = false

[start]
# Start the application
cmd = "npm start"
