version: '3.8'

services:
  floworx-app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - FRONTEND_URL=https://app.floworx-iq.com
    # Removed env_file to prevent .env.production from overriding runtime envs
    # env_file:
    #   - .env.production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add PostgreSQL if not using Supabase
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: floworx_db
  #     POSTGRES_USER: floworx_user
  #     POSTGRES_PASSWORD: your_secure_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: