name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

jobs:
  trigger-coolify:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Call Coolify Deploy Hook
      env:
        HOOK: ${{ secrets.COOLIFY_DEPLOY_HOOK }}
      run: |
        if [ -z "$HOOK" ]; then
          echo "COOLIFY_DEPLOY_HOOK not set"; exit 1;
        fi
        curl -fsS -X POST "$HOOK"
        echo "Deploy hook triggered."
